name: Spring demo GHA

on:
  push:
    branches:
      - master
    pull_request:
      - master


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout

      -  name: Setup JDK
         uses: actions/setup-java@v3
         with:
           java-version: '22'

      -   name: Build
          run: mvn clean install



